import tor.client.ClientSettings as cs
cs.RAMP_MATERIAL = "moss"
cs.RAMP_MATERIAL_HEIGHT = 30
cs.TRY_FINDING = True
cs.IMAGE_CROP_X_LEFT = 10
cs.IMAGE_CROP_X_RIGHT = 159
cs.IMAGE_CROP_Y_TOP = 325+67
cs.IMAGE_CROP_Y_BOTTOM = 247+95