version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)-19s | %(levelname)-8s | %(name)-25.25s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: TORClient.log
    maxBytes: 3145728   # 3 MB
    backupCount: 0      # delete old logs instead of keeping backups

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  Adafruit_I2C:
    level: INFO
    propagate: no
  TORClient.SerialCommunication:
    level: INFO
    propagate: no